import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Iprop = {
  children: React.ReactNode
  seo: React.ReactNode
}
export default function RootLayout({children}:Iprop) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className='nav_head'>Navigation Bar</h1>
        {children}
        <h1 className='footer'>Footer</h1>
        </body>

    </html>
  )
}
